apiVersion: aplicaciones / v1 
tipo: 
Metadatos de implementación : 
  nombre: {{.Release.Name}} 
  etiquetas: 
    aplicación: {{.Release.Name}} 
    categoría: microgateway 
spec: 
  réplicas: {{.Values.replicaCount}} 
  selector: 
    matchLabels : 
      aplicación: {{.Release.Name}} 
  plantilla: 
    metadatos: 
      etiquetas: 
        aplicación: {{.Release.Name}} 
      anotaciones: 
        prometheus.io/scrape: "{{.Values.metrics.prometheus}}" 
    especificación: 
      contenedores : 
        - nombre: {{.Release.Name}} 
          imagen: "{{.Values.image.repository}}: {{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}} 
          puertos: 
            - nombre: http 
              containerPort: {{.Values.image.containerPort}} 
              protocolo: TCP 
          livenessProbe: 
            exec: 
              comando: 
              - / bin / sh 
              - -c 
              - / opt /softwareag/Microgateway/files/k8s-lifenesscheck.sh 
            initialDelaySeconds: 10 
            periodSeconds: 10 
            timeoutSeconds: 5 
            failureThreshold: 3 
          readinessProbe: 
            exec: 
              command: 
              - / bin / sh 
              - -c
              - /opt/softwareag/Microgateway/files/k8s-readinesscheck.sh 
            initialDelaySeconds: 10 
            periodSeconds: 10 
            timeoutSeconds: 5 
            failureThreshold: 3 
        {{- if .Values.sidecarimage}} 
        - nombre: "{{.Values.sidecarimage.name} } " 
          imagen:" {{.Values.sidecarimage.repository}}: 
                  {{.Values.sidecarimage.tag}} " 
          imagePullPolicy: {{.Values.sidecarimage.pullPolicy}} 
        {{- end}} 
          recursos: 
            {{- toYaml .Values.resources | nindent 12}} 
      {{- con .Values.nodeSelector}} 
      nodeSelector: 
        {{- toYaml. | nindent 8}}
      {{- end}} 
    {{- con .Values.affinity}} 
      afinidad: 
        {{- toYaml. | nindent 8}} 
    {{- end}} 
    {{- con .Values.tolerations}} 
      tolerancias: 
        {{- toYaml. | nindent 8}} 
    {{- end}}