repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: dev
    namespace: dev
    chart: ./Chart
    values: 
      - ./charts/test-focus/dev.yaml

  - name: stage
    namespace: stage
    chart: ./Chart
    values: 
      - ./charts/test-focus/stage.yaml